import { defineType, defineField } from 'sanity'

export const uiStrings = defineType({
  name: 'uiStrings',
  title: 'UI Strings',
  type: 'document',
  fields: [
    defineField({
      name: 'formLabelName',
      type: 'string',
      title: 'Form: Label Name',
      initialValue: 'Name',
    }),
    defineField({
      name: 'formLabelEmail',
      type: 'string',
      title: 'Form: Label Email',
      initialValue: 'Email Address',
    }),
    defineField({
      name: 'formLabelMessage',
      type: 'string',
      title: 'Form: Label Message',
      initialValue: 'Message',
    }),
    defineField({
      name: 'formButtonSend',
      type: 'string',
      title: 'Form: Button Send',
      initialValue: 'Send',
    }),
    defineField({
      name: 'formSuccessMessage',
      type: 'text',
      title: 'Form: Success Message',
      initialValue: "Thanks for reaching out! I'll get back to you as soon as possible.",
    }),
    defineField({
      name: 'formGameLabelUserName',
      type: 'string',
      title: 'Form (Game): Label User Name',
      initialValue: 'User Name',
    }),
    defineField({
      name: 'formGamePlaceholderName',
      type: 'string',
      title: 'Form (Game): Placeholder Name',
      initialValue: 'Your name',
    }),
    defineField({
      name: 'formGamePlaceholderEmail',
      type: 'string',
      title: 'Form (Game): Placeholder Email',
      initialValue: 'you@example.com',
    }),
    defineField({
      name: 'formGamePlaceholderMessage',
      type: 'string',
      title: 'Form (Game): Placeholder Message',
      initialValue: 'Your message',
    }),
    defineField({
      name: 'formGameButtonSubmit',
      type: 'string',
      title: 'Form (Game): Button Submit',
      initialValue: 'Submit',
    }),
    defineField({
      name: 'formGameSuccessMessage',
      type: 'text',
      title: 'Form (Game): Success Message',
      initialValue:
        "Thanks for the feedback! If applicable, I'll get back to you pretty soon-ish.",
    }),
    defineField({
      name: 'formCodeButtonClear',
      type: 'string',
      title: 'Form (Code): Button Clear',
      initialValue: 'Clear',
    }),
    defineField({
      name: 'settingsTitle',
      type: 'string',
      title: 'Settings Modal: Title',
      initialValue: 'settings',
    }),
    defineField({
      name: 'settingsSubtitle',
      type: 'string',
      title: 'Settings Modal: Subtitle',
      initialValue: 'Game modes',
    }),
    defineField({
      name: 'settingsToggleAbout',
      type: 'string',
      title: 'Settings: Toggle About',
      initialValue: 'About Page Game Mode',
    }),
    defineField({
      name: 'settingsToggleAboutDesc',
      type: 'string',
      title: 'Settings: Toggle About Description',
      initialValue: 'Replaces the about content with character GUI',
    }),
    defineField({
      name: 'settingsToggleWork',
      type: 'string',
      title: 'Settings: Toggle Work',
      initialValue: 'Work Page Game Mode',
    }),
    defineField({
      name: 'settingsToggleWorkDesc',
      type: 'string',
      title: 'Settings: Toggle Work Description',
      initialValue: 'Replaces the work content with achievements GUI',
    }),
    defineField({
      name: 'settingsToggleWriting',
      type: 'string',
      title: 'Settings: Toggle Writing',
      initialValue: 'Writing Page Game Mode',
    }),
    defineField({
      name: 'settingsToggleWritingDesc',
      type: 'string',
      title: 'Settings: Toggle Writing Description',
      initialValue: 'Replaces the writing content with progress/activity log GUI',
    }),
    defineField({
      name: 'settingsToggleContact',
      type: 'string',
      title: 'Settings: Toggle Contact',
      initialValue: 'Contact Page Game Mode',
    }),
    defineField({
      name: 'settingsToggleContactDesc',
      type: 'string',
      title: 'Settings: Toggle Contact Description',
      initialValue: 'Replaces the contact content with feedback/bug report GUI',
    }),
    defineField({
      name: 'settingsToggleDelete',
      type: 'string',
      title: 'Settings: Toggle Delete',
      initialValue: 'Delete All Progress',
    }),
    defineField({
      name: 'settingsToggleDeleteDesc',
      type: 'string',
      title: 'Settings: Toggle Delete Description',
      initialValue: 'Deletes all achievements and progress',
    }),
    defineField({
      name: 'settingsButtonCancel',
      type: 'string',
      title: 'Settings: Button Cancel',
      initialValue: 'Cancel',
    }),
    defineField({
      name: 'settingsButtonDelete',
      type: 'string',
      title: 'Settings: Button Delete',
      initialValue: 'Delete',
    }),
    defineField({
      name: 'inventoryTitle',
      type: 'string',
      title: 'Inventory Modal: Title',
      initialValue: 'inventory',
    }),
    defineField({
      name: 'inventoryEmptyTitle',
      type: 'string',
      title: 'Inventory: Empty Title',
      initialValue: 'Your pockets are empty. For now.',
    }),
    defineField({
      name: 'inventoryEmptyMessage',
      type: 'text',
      title: 'Inventory: Empty Message',
      initialValue: 'Explore the site and the console. Some items await discovery.',
    }),
    defineField({
      name: 'inventoryButtonBack',
      type: 'string',
      title: 'Inventory: Button Back',
      initialValue: 'Back',
    }),
    defineField({
      name: 'inventoryButtonUse',
      type: 'string',
      title: 'Inventory: Button Use',
      initialValue: 'Use',
    }),
    defineField({
      name: 'themeModalTitle',
      type: 'string',
      title: 'Theme Modal: Title',
      initialValue: 'themes',
    }),
    defineField({
      name: 'themeLockedTooltip',
      type: 'string',
      title: 'Theme: Locked Tooltip',
      initialValue: "There's something hidden here...",
    }),
    defineField({
      name: 'themeLockMessage',
      type: 'string',
      title: 'Theme: Lock Message',
      initialValue: 'To change your theme unlock one color at minimum.',
    }),
    defineField({
      name: 'linkGithub',
      type: 'string',
      title: 'PageTitle: Link Github',
      initialValue: "Website's Github Profile",
    }),
    defineField({
      name: 'linkLinkedIn',
      type: 'string',
      title: 'PageTitle: Link LinkedIn',
      initialValue: 'LinkedIn Profile',
    }),
    defineField({
      name: 'linkThemes',
      type: 'string',
      title: 'PageTitle: Link Themes',
      initialValue: 'Themes',
    }),
    defineField({
      name: 'linkInventory',
      type: 'string',
      title: 'PageTitle: Link Inventory',
      initialValue: 'Inventory',
    }),
    defineField({
      name: 'linkSettings',
      type: 'string',
      title: 'PageTitle: Link Settings',
      initialValue: 'Settings',
    }),
    defineField({
      name: 'siteName',
      type: 'string',
      title: 'Site Name',
      initialValue: 'ryan canfield',
    }),
    defineField({
      name: 'notFoundMeta',
      type: 'string',
      title: '404: Meta',
      initialValue: '④⓪④',
    }),
    defineField({
      name: 'notFoundTitle',
      type: 'string',
      title: '404: Title',
      initialValue: '404',
    }),
    defineField({
      name: 'notFoundMessage',
      type: 'text',
      title: '404: Message',
      initialValue: "Oops! The page you're looking for doesn't exist (on this site anyway).",
    }),
    defineField({
      name: 'notFoundLink',
      type: 'string',
      title: '404: Link',
      initialValue: 'Go back to the home page',
    }),
    defineField({
      name: 'githubModalTitle',
      type: 'string',
      title: 'Github: Modal Title',
      initialValue: 'Github Contributions per day',
    }),
    defineField({
      name: 'githubModalSubtitle',
      type: 'string',
      title: 'Github: Modal Subtitle',
      initialValue: 'current to 2012',
    }),
    defineField({
      name: 'githubButtonLabel',
      type: 'string',
      title: 'Github: Button Label',
      initialValue: 'Github Contribution Graph',
    }),
    defineField({
      name: 'githubPollKeep',
      type: 'text',
      title: 'Github: Poll Keep Feedback',
      initialValue: "Yeah? Ok- I'll keep it. Thanks for the feedback.",
    }),
    defineField({
      name: 'githubPollRemove',
      type: 'text',
      title: 'Github: Poll Remove Feedback',
      initialValue: "You're probably right. I'll remove it. Thanks for the feedback.",
    }),
    defineField({
      name: 'cardTitleThemes',
      type: 'string',
      title: 'Writing Game: Card Title Themes',
      initialValue: 'Themes',
    }),
    defineField({
      name: 'cardTitleAchievements',
      type: 'string',
      title: 'Writing Game: Card Title Achievements',
      initialValue: 'Achievements',
    }),
    defineField({
      name: 'cardTitleLore',
      type: 'string',
      title: 'Writing Game: Card Title Lore',
      initialValue: 'Lore',
    }),
    defineField({
      name: 'loreCountTotal',
      type: 'number',
      title: 'Writing Game: Lore Count Total',
      description: 'Denominator for lore progress (e.g. 2/4)',
      initialValue: 4,
    }),
    defineField({
      name: 'loadingText',
      type: 'string',
      title: 'Loading: Default Text',
      initialValue: 'Loading...',
    }),
    defineField({
      name: 'loadingMessages',
      type: 'array',
      title: 'Loading: Rotating Messages',
      of: [{ type: 'string' }],
      description: 'Messages shown while Loading component fetches data',
      initialValue: [
        'Fetching data...',
        'Almost there...',
        'Hmmmmm...',
        'Ut oh..',
        '..🫠',
      ],
    }),
    defineField({
      name: 'ariaCloseModal',
      type: 'string',
      title: 'Aria: Close Modal',
      initialValue: 'Close modal',
    }),
    defineField({
      name: 'ariaClose',
      type: 'string',
      title: 'Aria: Close',
      initialValue: 'Close',
    }),
    defineField({
      name: 'ariaLockedTheme',
      type: 'string',
      title: 'Aria: Locked Theme',
      initialValue: 'Locked theme',
    }),
    defineField({
      name: 'ariaLockColor',
      type: 'string',
      title: 'Aria: Lock Color',
      initialValue: 'Lock color',
    }),
    defineField({
      name: 'ariaHome',
      type: 'string',
      title: 'Aria: Home',
      initialValue: 'Home',
    }),
    defineField({
      name: 'ariaCodeDigitTemplate',
      type: 'string',
      title: 'Aria: Code Digit Template',
      description: 'Use {n} for digit index, e.g. "Code Digit {n}"',
      initialValue: 'Code Digit {n}',
    }),
    defineField({
      name: 'caseStudyProblem',
      type: 'string',
      title: 'Case Study: Problem Section Heading',
      initialValue: 'Problem Analysis',
    }),
    defineField({
      name: 'caseStudySolution',
      type: 'string',
      title: 'Case Study: Solution Section Heading',
      initialValue: 'Solution',
    }),
    defineField({
      name: 'caseStudyResult',
      type: 'string',
      title: 'Case Study: Result Section Heading',
      initialValue: 'Result',
    }),
    defineField({
      name: 'workSectionOpenSource',
      type: 'string',
      title: 'Work: Open Source Section Heading',
      initialValue: 'open source',
    }),
    defineField({
      name: 'aboutSectionMeta',
      type: 'string',
      title: 'About: Meta Section Heading',
      initialValue: 'meta',
    }),
    defineField({
      name: 'loginButtonGithub',
      type: 'string',
      title: 'Login: Button Label (GitHub)',
      initialValue: 'Log in with Github',
    }),
    defineField({
      name: 'colorCopy',
      type: 'string',
      title: 'Color Menu: Copy Action',
      initialValue: 'Copy color',
    }),
    defineField({
      name: 'colorLock',
      type: 'string',
      title: 'Color Menu: Lock Action',
      initialValue: 'Lock color',
    }),
    defineField({
      name: 'colorChooseNew',
      type: 'string',
      title: 'Color Menu: Choose New Action',
      initialValue: 'Choose new color',
    }),
    defineField({
      name: 'colorCopiedToast',
      type: 'string',
      title: 'Color Menu: Copied Toast Message',
      initialValue: 'Color copied!',
    }),
  ],
})
