/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as StudioSplatRouteImport } from './routes/studio.$'
import { Route as ApiThemePickerRouteImport } from './routes/api/theme-picker'
import { Route as ApiGithubContributionsRouteImport } from './routes/api/github-contributions'
import { Route as ApiGetAchievementsRouteImport } from './routes/api/get-achievements'
import { Route as ApiDeleteAchievementsRouteImport } from './routes/api/delete-achievements'
import { Route as ApiAddAchievementRouteImport } from './routes/api/add-achievement'
import { Route as AppChar9466Char9463Char9467Char9464RouteImport } from './routes/_app.⓺⓷⓻⓸'
import { Route as AppWritingRouteImport } from './routes/_app.writing'
import { Route as AppWorkRouteImport } from './routes/_app.work'
import { Route as AppJourneyToEryndorRouteImport } from './routes/_app.journey-to-eryndor'
import { Route as AppContactRouteImport } from './routes/_app.contact'
import { Route as AppAboutRouteImport } from './routes/_app.about'
import { Route as App6374RouteImport } from './routes/_app.6374'
import { Route as AppWorkIndexRouteImport } from './routes/_app.work.index'
import { Route as AppWorkIdRouteImport } from './routes/_app.work.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const StudioSplatRoute = StudioSplatRouteImport.update({
  id: '/studio/$',
  path: '/studio/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThemePickerRoute = ApiThemePickerRouteImport.update({
  id: '/api/theme-picker',
  path: '/api/theme-picker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubContributionsRoute = ApiGithubContributionsRouteImport.update({
  id: '/api/github-contributions',
  path: '/api/github-contributions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetAchievementsRoute = ApiGetAchievementsRouteImport.update({
  id: '/api/get-achievements',
  path: '/api/get-achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeleteAchievementsRoute = ApiDeleteAchievementsRouteImport.update({
  id: '/api/delete-achievements',
  path: '/api/delete-achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddAchievementRoute = ApiAddAchievementRouteImport.update({
  id: '/api/add-achievement',
  path: '/api/add-achievement',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChar9466Char9463Char9467Char9464Route =
  AppChar9466Char9463Char9467Char9464RouteImport.update({
    id: '/⓺⓷⓻⓸',
    path: '/⓺⓷⓻⓸',
    getParentRoute: () => AppRoute,
  } as any)
const AppWritingRoute = AppWritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkRoute = AppWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AppRoute,
} as any)
const AppJourneyToEryndorRoute = AppJourneyToEryndorRouteImport.update({
  id: '/journey-to-eryndor',
  path: '/journey-to-eryndor',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const App6374Route = App6374RouteImport.update({
  id: '/6374',
  path: '/6374',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkIndexRoute = AppWorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkRoute,
} as any)
const AppWorkIdRoute = AppWorkIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppWorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof AppIndexRoute
  '/6374': typeof App6374Route
  '/about': typeof AppAboutRoute
  '/contact': typeof AppContactRoute
  '/journey-to-eryndor': typeof AppJourneyToEryndorRoute
  '/work': typeof AppWorkRouteWithChildren
  '/writing': typeof AppWritingRoute
  '/⓺⓷⓻⓸': typeof AppChar9466Char9463Char9467Char9464Route
  '/api/add-achievement': typeof ApiAddAchievementRoute
  '/api/delete-achievements': typeof ApiDeleteAchievementsRoute
  '/api/get-achievements': typeof ApiGetAchievementsRoute
  '/api/github-contributions': typeof ApiGithubContributionsRoute
  '/api/theme-picker': typeof ApiThemePickerRoute
  '/studio/$': typeof StudioSplatRoute
  '/work/$id': typeof AppWorkIdRoute
  '/work/': typeof AppWorkIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/6374': typeof App6374Route
  '/about': typeof AppAboutRoute
  '/contact': typeof AppContactRoute
  '/journey-to-eryndor': typeof AppJourneyToEryndorRoute
  '/writing': typeof AppWritingRoute
  '/⓺⓷⓻⓸': typeof AppChar9466Char9463Char9467Char9464Route
  '/api/add-achievement': typeof ApiAddAchievementRoute
  '/api/delete-achievements': typeof ApiDeleteAchievementsRoute
  '/api/get-achievements': typeof ApiGetAchievementsRoute
  '/api/github-contributions': typeof ApiGithubContributionsRoute
  '/api/theme-picker': typeof ApiThemePickerRoute
  '/studio/$': typeof StudioSplatRoute
  '/': typeof AppIndexRoute
  '/work/$id': typeof AppWorkIdRoute
  '/work': typeof AppWorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/6374': typeof App6374Route
  '/_app/about': typeof AppAboutRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/journey-to-eryndor': typeof AppJourneyToEryndorRoute
  '/_app/work': typeof AppWorkRouteWithChildren
  '/_app/writing': typeof AppWritingRoute
  '/_app/⓺⓷⓻⓸': typeof AppChar9466Char9463Char9467Char9464Route
  '/api/add-achievement': typeof ApiAddAchievementRoute
  '/api/delete-achievements': typeof ApiDeleteAchievementsRoute
  '/api/get-achievements': typeof ApiGetAchievementsRoute
  '/api/github-contributions': typeof ApiGithubContributionsRoute
  '/api/theme-picker': typeof ApiThemePickerRoute
  '/studio/$': typeof StudioSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/work/$id': typeof AppWorkIdRoute
  '/_app/work/': typeof AppWorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/6374'
    | '/about'
    | '/contact'
    | '/journey-to-eryndor'
    | '/work'
    | '/writing'
    | '/⓺⓷⓻⓸'
    | '/api/add-achievement'
    | '/api/delete-achievements'
    | '/api/get-achievements'
    | '/api/github-contributions'
    | '/api/theme-picker'
    | '/studio/$'
    | '/work/$id'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/6374'
    | '/about'
    | '/contact'
    | '/journey-to-eryndor'
    | '/writing'
    | '/⓺⓷⓻⓸'
    | '/api/add-achievement'
    | '/api/delete-achievements'
    | '/api/get-achievements'
    | '/api/github-contributions'
    | '/api/theme-picker'
    | '/studio/$'
    | '/'
    | '/work/$id'
    | '/work'
  id:
    | '__root__'
    | '/$'
    | '/_app'
    | '/_app/6374'
    | '/_app/about'
    | '/_app/contact'
    | '/_app/journey-to-eryndor'
    | '/_app/work'
    | '/_app/writing'
    | '/_app/⓺⓷⓻⓸'
    | '/api/add-achievement'
    | '/api/delete-achievements'
    | '/api/get-achievements'
    | '/api/github-contributions'
    | '/api/theme-picker'
    | '/studio/$'
    | '/_app/'
    | '/_app/work/$id'
    | '/_app/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  ApiAddAchievementRoute: typeof ApiAddAchievementRoute
  ApiDeleteAchievementsRoute: typeof ApiDeleteAchievementsRoute
  ApiGetAchievementsRoute: typeof ApiGetAchievementsRoute
  ApiGithubContributionsRoute: typeof ApiGithubContributionsRoute
  ApiThemePickerRoute: typeof ApiThemePickerRoute
  StudioSplatRoute: typeof StudioSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/studio/$': {
      id: '/studio/$'
      path: '/studio/$'
      fullPath: '/studio/$'
      preLoaderRoute: typeof StudioSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/theme-picker': {
      id: '/api/theme-picker'
      path: '/api/theme-picker'
      fullPath: '/api/theme-picker'
      preLoaderRoute: typeof ApiThemePickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-contributions': {
      id: '/api/github-contributions'
      path: '/api/github-contributions'
      fullPath: '/api/github-contributions'
      preLoaderRoute: typeof ApiGithubContributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/get-achievements': {
      id: '/api/get-achievements'
      path: '/api/get-achievements'
      fullPath: '/api/get-achievements'
      preLoaderRoute: typeof ApiGetAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delete-achievements': {
      id: '/api/delete-achievements'
      path: '/api/delete-achievements'
      fullPath: '/api/delete-achievements'
      preLoaderRoute: typeof ApiDeleteAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/add-achievement': {
      id: '/api/add-achievement'
      path: '/api/add-achievement'
      fullPath: '/api/add-achievement'
      preLoaderRoute: typeof ApiAddAchievementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/⓺⓷⓻⓸': {
      id: '/_app/⓺⓷⓻⓸'
      path: '/⓺⓷⓻⓸'
      fullPath: '/⓺⓷⓻⓸'
      preLoaderRoute: typeof AppChar9466Char9463Char9467Char9464RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/writing': {
      id: '/_app/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof AppWritingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/work': {
      id: '/_app/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof AppWorkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journey-to-eryndor': {
      id: '/_app/journey-to-eryndor'
      path: '/journey-to-eryndor'
      fullPath: '/journey-to-eryndor'
      preLoaderRoute: typeof AppJourneyToEryndorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/6374': {
      id: '/_app/6374'
      path: '/6374'
      fullPath: '/6374'
      preLoaderRoute: typeof App6374RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/work/': {
      id: '/_app/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof AppWorkIndexRouteImport
      parentRoute: typeof AppWorkRoute
    }
    '/_app/work/$id': {
      id: '/_app/work/$id'
      path: '/$id'
      fullPath: '/work/$id'
      preLoaderRoute: typeof AppWorkIdRouteImport
      parentRoute: typeof AppWorkRoute
    }
  }
}

interface AppWorkRouteChildren {
  AppWorkIdRoute: typeof AppWorkIdRoute
  AppWorkIndexRoute: typeof AppWorkIndexRoute
}

const AppWorkRouteChildren: AppWorkRouteChildren = {
  AppWorkIdRoute: AppWorkIdRoute,
  AppWorkIndexRoute: AppWorkIndexRoute,
}

const AppWorkRouteWithChildren =
  AppWorkRoute._addFileChildren(AppWorkRouteChildren)

interface AppRouteChildren {
  App6374Route: typeof App6374Route
  AppAboutRoute: typeof AppAboutRoute
  AppContactRoute: typeof AppContactRoute
  AppJourneyToEryndorRoute: typeof AppJourneyToEryndorRoute
  AppWorkRoute: typeof AppWorkRouteWithChildren
  AppWritingRoute: typeof AppWritingRoute
  AppChar9466Char9463Char9467Char9464Route: typeof AppChar9466Char9463Char9467Char9464Route
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  App6374Route: App6374Route,
  AppAboutRoute: AppAboutRoute,
  AppContactRoute: AppContactRoute,
  AppJourneyToEryndorRoute: AppJourneyToEryndorRoute,
  AppWorkRoute: AppWorkRouteWithChildren,
  AppWritingRoute: AppWritingRoute,
  AppChar9466Char9463Char9467Char9464Route:
    AppChar9466Char9463Char9467Char9464Route,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  ApiAddAchievementRoute: ApiAddAchievementRoute,
  ApiDeleteAchievementsRoute: ApiDeleteAchievementsRoute,
  ApiGetAchievementsRoute: ApiGetAchievementsRoute,
  ApiGithubContributionsRoute: ApiGithubContributionsRoute,
  ApiThemePickerRoute: ApiThemePickerRoute,
  StudioSplatRoute: StudioSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
